# Generated by Django 6.0.7 on 2026-07-24 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBetResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_date', models.DateField(unique=True, verbose_name='Data do jogo')),
                ('concurso', models.PositiveIntegerField(blank=True, null=True, verbose_name='Concurso')),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor investido')),
                ('returned_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor retornado')),
                ('notes', models.TextField(blank=True, verbose_name='Observacao')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resultado diario',
                'verbose_name_plural': 'Resultados diarios',
                'ordering': ['-play_date'],
            },
        ),
    ]
