# Generated by Django 6.0.7 on 2026-07-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybetresult',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desativado em'),
        ),
        migrations.AddField(
            model_name='dailybetresult',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='dailybetresult',
            name='play_date',
            field=models.DateField(verbose_name='Data do jogo'),
        ),
        migrations.AddConstraint(
            model_name='dailybetresult',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('play_date',), name='unique_active_daily_bet_result_date'),
        ),
    ]
