# Generated by Django 6.0.7 on 2026-08-05 23:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_dailybetresult_deactivated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetConferenceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.CharField(choices=[('auto', 'Automatico'), ('manual', 'Manual')], default='auto', max_length=10, verbose_name='Disparado por')),
                ('checked_count', models.PositiveIntegerField(default=0, verbose_name='Jogos conferidos')),
                ('contemplated_count', models.PositiveIntegerField(default=0, verbose_name='Jogos contemplados')),
            ],
            options={
                'verbose_name': 'Execucao de conferencia',
                'verbose_name_plural': 'Execucoes de conferencia',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dezenas', models.JSONField(verbose_name='Dezenas apostadas')),
                ('concurso', models.PositiveIntegerField(blank=True, null=True, verbose_name='Concurso')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor apostado')),
                ('source', models.CharField(choices=[('ai', 'Gerado pela IA'), ('manual', 'Manual')], default='ai', max_length=10, verbose_name='Origem')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Pontuacao do modelo')),
                ('rationale', models.TextField(blank=True, verbose_name='Justificativa da IA')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Conferido')),
                ('is_contemplated', models.BooleanField(default=False, verbose_name='Contemplado')),
                ('hits_count', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(15)], verbose_name='Quantidade de acertos')),
                ('matched_numbers', models.JSONField(blank=True, null=True, verbose_name='Dezenas acertadas')),
                ('prize_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor do premio')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Conferido em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='analyzer.dailybetresult', verbose_name='Registro diario')),
            ],
            options={
                'verbose_name': 'Jogo confirmado',
                'verbose_name_plural': 'Jogos confirmados',
                'ordering': ['-created_at'],
            },
        ),
    ]
